### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by NikkyAI** [DaemonicLabs/KNote#3]
This Issue can collect `TODO`'s
and link to more specific issues

# Core

- [ ] global default imports in a notebook (if IDE supports it)
- [ ] Shrink page dependencies declaration if possible (especially type declaration)
  - [ ] Try out `@File:UsePage(pageId)`  
        will cause process to execute during IDE highlighting too
- [ ] Compile static file (Markdown / HTML) output

# Scripts

- [ ] add visualization transformation functions to scripts or notebooks

# GUI

- [ ] bind gui data to observable notebooks and pages list
- [ ] monspaced font for results
- [ ] Go To `dependencies` and `dependents` buttons (between pages)
- [ ] allow switching between notebooks
